name: CI
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - "v*.*.*"

jobs:
  check:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: bufbuild/buf-setup-action@v1.34.0
      name: Setup buf
    - uses: bufbuild/buf-lint-action@v1
      name: Buf Lint
    - uses: bufbuild/buf-breaking-action@v1
      name: Buf Breaking Detect
      with:
        against: 'https://github.com/imvancer/apis.git#branch=main,ref=HEAD~1'
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    needs: check
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    strategy:
      matrix:
        lang: ["go"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.22.4' # The Go version to download (if necessary) and use.
    - uses: bufbuild/buf-setup-action@v1.34.0
      name: Setup buf
    - name: Install Plugins
      run: make tools
    - name: Setup git
      run: |
        git config user.name "github action bot"
        git config user.email "bot@imvancer.com"
    - name: Generate Stub Package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p gen/${{ matrix.lang }}
        git clone https://user:$GITHUB_TOKEN@github.com/imvancer/gen${{ matrix.lang }}.git
        find gen/${{ matrix.lang }} -type f -regex '.*\(.go\|.py\|.pyc\|.java\)$' -delete
        find gen/${{ matrix.lang }} -type d -empty -delete
        buf generate
        test -f scripts/precommit_${{ matrix.lang }}.sh && ./scripts/precommit_${{ matrix.lang }}.sh
        cd gen/${{ matrix.lang }}
        git add . && git diff-index --quiet HEAD || git commit -m "automatically generated by github action" && git tag ${{ github.ref_name }} && git push -f origin main --tags
