name: CI
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - "v*.*.*"

jobs:
  buf:
    name: Lint and Generate Stub Packages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: bufbuild/buf-setup-action@v1.34.0
      name: Setup buf
    - uses: bufbuild/buf-lint-action@v1
